project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    - "!classroom/"
  

website:
  title: "SFC6006"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: Labs
        menu:
          - href: labs/Semaine1.qmd
            text: Semaine 1
          - href: labs/Semaine2.qmd
            text: Semaine 2
          - href: labs/Semaine3.qmd
            text: Semaine 3
          - href: examen/examen.qmd
            text: Examen
      - about.qmd

format:
  html:
    theme: 
      - sandstone
      - website-styles.scss

    toc: true

bibliography: template/references.bib
csl: template/apa-fr.csl